services:
  - name: mongodb
  - name: rocketchat
  - name: traefik

mongodb_version: 5.0
rocket.chat_version: 5.0
traefik_version: 2.8
rocket_chat_url: https://your-domain.com
my_email: your-email@gmail.com
traefik_pass: yours-pass