---
- name: Deploy Rocket.chat
  block:
    - name: Creating volumes
      docker_volume:
        name: "{{ item }}"
      loop: "{{ volumes }}"

    - name: Выкладка сервиса
      include_tasks: "../services/{{ item.name }}/service.yml"
      loop: "{{ services }}"
